  version: '3'
  services:
    flask-app:
      build:
        context: .
      ports:
        - "5001:5000"
      depends_on:
        - rabbitmq
      volumes:
        - ./data:/app/data

    rabbitmq:
      image: "rabbitmq:3-management"
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        RABBITMQ_DEFAULT_USER: "username"
        RABBITMQ_DEFAULT_PASS: "password"